// solsim-client/src/app/header/header.component.ts
import { Component } from '@angular/core';
import { PerformanceComponent } from '../performance/performance.component';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [PerformanceComponent],
  templateUrl: './header.component.html',
  styleUrl: './header.component.css'
})
export class HeaderComponent {

}

<header class="header">
    <h3>SolSim3</h3>
    <label>
      Star Systems: 
      <select name="selectedSystem">
        <option>Option 1</option>
        <option>Option 2</option>
      </select> 
    </label>
    
    <label>
      Granularity: 
      <select name="selectedGranularity">
        <option>Option 1</option>
        <option>Option 2</option>
      </select> 
    </label>

    <div class = 'perfContainer'>
        <app-performance/>
    </div>
</header>

// solsim-client/src/components/Header.tsx
import React, { useEffect, useRef, useState } from 'react';
import Performance from './Performance'; // Adjust the path according to your project structure

const Header: React.FC = () => {
  return (
    <header className="header">
      <h3>SolSim3</h3>
      <label>
        Star Systems: 
        <select name="selectedSystem">
          <option>Option 1</option>
          <option>Option 2</option>
        </select> 
      </label>
      
      <label>
        Granularity: 
        <select name="selectedGranularity">
          <option>Option 1</option>
          <option>Option 2</option>
        </select> 
      </label>

      <Performance />
    </header>
  );
};

export default Header;
