// solsim-client/src/components/Footer.tsx
import React, { useEffect, useState } from 'react';
import orbitService from '../services/orbitService';

const Footer: React.FC = () => {

  let [runningState, setRunningState] = useState(true)

  const handleStart = () => {
    orbitService.connectWebSocket();
    setRunningState(true)
  };

  const handleStop = () => {
    orbitService.disconnectWebSocket();
    setRunningState(false)
  };

  useEffect(() => {
    const subscription = orbitService.getIsRunningObservable().subscribe(s => {
      setRunningState(s);
    });

    // Cleanup subscription on component unmount
    return () => subscription.unsubscribe();
  }, []);
  
  return (
    <footer className="footer">
      <div>
        <button className="solSimButton">Recenter</button>
        <br />
        <button className="solSimButton">Something</button>

      </div>

      <div className='StartStopContainer'>
        <button className={runningState ? 'startStop stop' : 'startStop start' } onClick={runningState ? handleStop : handleStart}>
          {runningState ? "STOP" : "START"}
        </button>
      </div>


      <div>
        <button className="solSimButton">Reset Paths</button>
        <button className="solSimButton">Toggle Paths
          
        </button>
        <br />
        <button className="solSimButton">Toggle Vectors</button>
        <button className="solSimButton">Toggle Grid </button>
      </div>

    </footer>
  );
};

export default Footer;

// solsim-client/src/app/footer/footer.component.ts
import { Component } from '@angular/core';
import { OrbitService } from '../services/orbit.service';
import { ControlsService } from '../services/controls.service';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [],
  templateUrl: './footer.component.html',
  styleUrl: './footer.component.css'
})
export class FooterComponent {

  isConnected = false;

  constructor(private orbs: OrbitService, private ctrl: ControlsService ) {
    this.orbs.connectionStatus$.subscribe(status => {
      this.isConnected = status;
    });
  }

  toggleConnection() {
    if (this.isConnected) {
      this.orbs.disconnectWebSocket();
    } else {
      this.orbs.connectWebSocket();
    }
  }

  togglePaths() {
    this.ctrl.togglePaths();
  }

  resetPaths() {
    this.ctrl.resetPaths();
  }

  recenter() {
    this.ctrl.recenter();
  }
}

<footer class="footer">
    <div>
      <button class="solSimButton" (click)="recenter()">Recenter</button>
      <br />
      <button class="solSimButton">Something</button>

    </div>

    <div class='StartStopContainer' >
      <button class= "{{ isConnected ? 'startStop stop' : 'startStop' }}" (click)="toggleConnection()">
        {{ isConnected ? 'Stop' : 'Start' }}
    </button>
    </div>


    <div>
      <button class="solSimButton" (click)="togglePaths()">Toggle Paths</button>
      <button class="solSimButton" (click)="resetPaths()">Reset Paths</button>
        
      <br />
      <!-- <button class="solSimButton">Toggle Vectors</button>
      <button class="solSimButton">Toggle Grid </button> -->
    </div>

  </footer>
